# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1858858056c455742866b904220ebf69a27a573b0404b1568724e842a8ecc009c83b7a35db7105bce51cb3bbe90932d9a0275b64169088378056853e812d4f54

test:
  secret_key_base: 220116747b5fea8f04eba111bd38d5b2c22d726fe5714aef399573b505bd0df03db6278226dac98e5073ae56d36055e3dbe96449efa10b7c29ab76705d5ba42a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
